# setup.ps1 - Sets up VHC Monitor on Windows
# Usage: .\setup.ps1 -AlertUrl "https://ntfy.example.com/veeam-alerts"
# Requires: vhc-monitor.exe in the same directory as this script, or in dist\

param(
    [Parameter(Mandatory=$false)]
    [string]$AlertUrl,

    [Parameter(Mandatory=$false)]
    [int]$IntervalMinutes = 5,

    [Parameter(Mandatory=$false)]
    [string]$InstallDir = "$env:ProgramFiles\VHC"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  VHC Monitor Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# --- 1. Locate and copy vhc-monitor.exe ---
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$exeCandidates = @(
    (Join-Path $scriptDir "vhc-monitor.exe"),
    (Join-Path $scriptDir "dist\vhc-monitor.exe")
)

$exeSource = $null
foreach ($candidate in $exeCandidates) {
    if (Test-Path $candidate) {
        $exeSource = $candidate
        break
    }
}

if (-not $exeSource) {
    Write-Host "ERROR: vhc-monitor.exe not found." -ForegroundColor Red
    Write-Host "Place it next to this script or in dist\vhc-monitor.exe" -ForegroundColor Red
    Write-Host "Build it first with: .\build.ps1" -ForegroundColor Yellow
    exit 1
}

Write-Host "[1/5] Copying vhc-monitor.exe to $InstallDir" -ForegroundColor Yellow
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}
Copy-Item $exeSource (Join-Path $InstallDir "vhc-monitor.exe") -Force
Write-Host "  -> Copied to $InstallDir\vhc-monitor.exe" -ForegroundColor Green

# --- 2. Generate config from user input ---
Write-Host ""
Write-Host "[2/5] Configuring monitoring targets" -ForegroundColor Yellow

$configPath = Join-Path $InstallDir "vhc-monitor.yaml"

# Prompt for VBR server
$vbrUrl = Read-Host "  VBR server URL (e.g. https://vbr-server:9419, or blank to skip)"
$vbrBlock = ""
if ($vbrUrl) {
    $vbrUser = Read-Host "  VBR username (e.g. DOMAIN\backupadmin)"
    $vbrPass = Read-Host "  VBR password" -AsSecureString
    $vbrPassPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($vbrPass)
    )
    $vbrBlock = @"
  - name: vbr
    type: vbr
    url: $vbrUrl
    username: "$vbrUser"
    password: "$vbrPassPlain"
    verify_ssl: false
"@
}

# Prompt for VBAWS server
$vbawsUrl = Read-Host "  VBAWS server URL (e.g. https://vbaws-appliance, or blank to skip)"
$vbawsBlock = ""
if ($vbawsUrl) {
    $vbawsUser = Read-Host "  VBAWS username"
    $vbawsPass = Read-Host "  VBAWS password" -AsSecureString
    $vbawsPassPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($vbawsPass)
    )
    $vbawsBlock = @"
  - name: vbaws
    type: vbaws
    url: $vbawsUrl
    username: "$vbawsUser"
    password: "$vbawsPassPlain"
    verify_ssl: false
"@
}

if (-not $vbrUrl -and -not $vbawsUrl) {
    Write-Host "  WARNING: No servers configured. Edit $configPath manually." -ForegroundColor Yellow
}

# Build output section
$outputBlock = "output:`n  - type: json_stdout"
if ($AlertUrl) {
    $outputBlock += @"

  - type: webhook
    url: $AlertUrl
    template: ntfy
    min_severity: warning
    deduplicate: true
"@
}

$logPath = Join-Path $InstallDir "vhc-monitor.log"
$statePath = Join-Path $InstallDir "vhc-monitor-state.json"

$configContent = @"
# VHC Monitor configuration
# Generated by setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

global:
  timeout_seconds: 30
  retry_count: 2
  retry_delay_seconds: 5
  state_file: "$($statePath -replace '\\', '\\')"
  logging:
    level: INFO
    file: "$($logPath -replace '\\', '\\')"
    rotation_when: midnight
    rotation_interval: 1
    rotation_keep: 30
    console: false
    disk_warning_mb: 500

servers:
$vbrBlock
$vbawsBlock

$outputBlock

repo_health:
  enabled: true
  thresholds:
    free_space_warning_pct: 15
    free_space_critical_pct: 5

retention:
  enabled: true
  thresholds:
    overage_multiplier: 1.5
    max_age_multiplier: 1.5
    orphan_detection: true

worker_health:
  enabled: true
  lookback_hours: 24
  thresholds:
    session_failure_rate_warning: 0.1
    session_failure_rate_critical: 0.3
    zero_deleted_items_warning: true
    recurring_failure_threshold: 3

error_patterns:
  - pattern: "Access Key Id you provided does not exist"
    severity: critical
    message: "AWS Access Key expired or deleted"
    category: credential
  - pattern: "not enough free addresses in subnet"
    severity: critical
    message: "Subnet IP exhaustion"
    category: network
  - pattern: "Invalid credentials"
    severity: critical
    message: "Invalid credentials"
    category: credential
"@

$configContent | Out-File -FilePath $configPath -Encoding utf8
Write-Host "  -> Config written to $configPath" -ForegroundColor Green

# --- 3. Create Task Scheduler job ---
Write-Host ""
Write-Host "[3/5] Creating scheduled task" -ForegroundColor Yellow

$taskName = "VHC Monitor"
$exeFullPath = Join-Path $InstallDir "vhc-monitor.exe"
$taskAction = New-ScheduledTaskAction `
    -Execute $exeFullPath `
    -Argument "all --config `"$configPath`"" `
    -WorkingDirectory $InstallDir

$taskTrigger = New-ScheduledTaskTrigger `
    -Once `
    -At (Get-Date) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes) `
    -RepetitionDuration (New-TimeSpan -Days 9999)

$taskSettings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -DontStopOnIdleEnd `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

$taskPrincipal = New-ScheduledTaskPrincipal `
    -UserId "SYSTEM" `
    -LogonType ServiceAccount `
    -RunLevel Highest

# Remove existing task if present
if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    Write-Host "  -> Removed existing '$taskName' task" -ForegroundColor Yellow
}

Register-ScheduledTask `
    -TaskName $taskName `
    -Action $taskAction `
    -Trigger $taskTrigger `
    -Settings $taskSettings `
    -Principal $taskPrincipal `
    -Description "Monitors Veeam backup infrastructure health every $IntervalMinutes minutes" | Out-Null

Write-Host "  -> Scheduled task '$taskName' created (every $IntervalMinutes min)" -ForegroundColor Green

# --- 4. Run once to test ---
Write-Host ""
Write-Host "[4/5] Running initial test..." -ForegroundColor Yellow

try {
    $testResult = & $exeFullPath version 2>&1
    Write-Host "  -> $testResult" -ForegroundColor Green
} catch {
    Write-Host "  -> WARNING: Test run failed: $_" -ForegroundColor Yellow
    Write-Host "  -> The scheduled task is still configured. Check config and try manually." -ForegroundColor Yellow
}

# --- 5. Success ---
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  Setup Complete" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Install dir:  $InstallDir" -ForegroundColor White
Write-Host "  Config:       $configPath" -ForegroundColor White
Write-Host "  Log file:     $logPath" -ForegroundColor White
Write-Host "  Schedule:     Every $IntervalMinutes minutes" -ForegroundColor White
if ($AlertUrl) {
    Write-Host "  Alerts:       $AlertUrl" -ForegroundColor White
}
Write-Host ""
Write-Host "  Manual run:   & '$exeFullPath' all --config '$configPath'" -ForegroundColor Cyan
Write-Host "  View logs:    Get-Content '$logPath' -Tail 50" -ForegroundColor Cyan
Write-Host "  Edit config:  notepad '$configPath'" -ForegroundColor Cyan
Write-Host ""
