# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for vhc-monitor standalone executable

a = Analysis(
    ['vhc_monitor/cli.py'],
    pathex=[],
    binaries=[],
    datas=[('config/example.yaml', 'config')],
    hiddenimports=[
        'vhc_monitor',
        'vhc_monitor.core',
        'vhc_monitor.core.auth',
        'vhc_monitor.core.client_vbr',
        'vhc_monitor.core.client_vbaws',
        'vhc_monitor.core.client_em',
        'vhc_monitor.core.config',
        'vhc_monitor.core.logging',
        'vhc_monitor.core.models',
        'vhc_monitor.core.output',
        'vhc_monitor.core.patterns',
        'vhc_monitor.core.powershell',
        'vhc_monitor.core.state',
        'vhc_monitor.monitors',
        'vhc_monitor.monitors.base',
        'vhc_monitor.monitors.repo_health',
        'vhc_monitor.monitors.retention',
        'vhc_monitor.monitors.worker_health',
        'vhc_monitor.outputs',
        'vhc_monitor.outputs.email',
        'vhc_monitor.outputs.json_file',
        'vhc_monitor.outputs.json_stdout',
        'vhc_monitor.outputs.prometheus',
        'vhc_monitor.outputs.webhook',
        'yaml',
        'typer',
        'rich',
        'httpx',
        'prometheus_client',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    a.zipfiles,
    name='vhc-monitor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
